name: job_time
description: Job Timer controlador de Tempo de Trabalho.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  asuka: ^2.0.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  google_sign_in: ^6.1.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  modular_bloc_bind: ^1.0.1
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  validatorless: ^1.2.3

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf
